# Basic Information
title: Honghui Bao
position: PhD Student
affiliation: University of Illinois Chicago
affiliation_link: https://cs.uic.edu/
email: honghuibao2000 (at) gmail.com / hbao (at) uic.edu

# Search Engine Optimization (SEO)
keywords: Honghui Bao, recommender systems, large language models, NUS, NExT++, UIC, Philip Yu
description: Honghui Bao's website
canonical: https://honghuibao2000.github.io/

# Links
google_scholar: https://scholar.google.com/citations?user=wIP-aZIAAAAJ
cv_link:
github_link: https://github.com/HonghuiBao2000
linkedin: https://www.linkedin.com/in/honghui-bao-7b71a7342/
twitter: https://x.com/HonghuiBao

# Images
avatar: ./assets/img/prof_pic.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: false

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Serif"

collections:
  projects:
    output: true
    permalink: /:name.html

# Google Analytics ID
# google_analytics:

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
